---
name: Sphinx CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        default: '${{ github.ref }}'
        description: Tag to build
        required: false
        type: string
      target:
        description: Target to build
        required: true
        type: string
        default: "html"
      env:
        description: Environment variables
        required: false
        type: string
        default: ""
      upload_artifact:
        description: Upload artifact
        required: false
        type: boolean
        default: false
    secrets:
      token:
        description: PAT
        required: false

env:
  DEFAULT_PYTHON: "3.10"

jobs:
  mainbuild:
    name: Check build
    runs-on: ubuntu-latest 
#[ self-hosted ]
    timeout-minutes: 30
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          token: ${{ secrets.token == null && secrets.GITHUB_TOKEN || secrets.token }}
          fetch-depth: 0

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Set up virtualenv
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt

      - name: Check cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install python modules
        run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Clean old build
        run: rm -rf _build
             echo ${{ github.event.inputs.env }}

      - uses: hmarr/debug-action@v2

      - name: 🚀 Build CI
        run: |
          make ${{ inputs.target }} ${{ inputs.env }}  2> >(tee warning.txt)
          [[ -s warning.txt ]] && echo ---------------------- Found warnings in build ---------------------- && exit 1
 

      - name: ℹ️ Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ inputs.upload_artifact }}
        with:
          name: HTMLOutput
          path: |
            _build/html
